### ISSUE TITLE
http://swiftcomparsion.qiniudn.com (like C#) is broken

### ISSUE THREAD

**Issue by bofeiw** [jiyinyiyong/swift-is-like-go#9]

**Comment by jiyinyiyong** [comment]
Not under my radar... what's happening?

**Comment by bofeiw** [comment]
@jiyinyiyong In your Readme.md, you wrote "inspired by" this link (C#). However when you go to this link, it says `{"error":"no such domain"}`.

**Comment by jiyinyiyong** [comment]
Maybe I can replace it some https://myquay.github.io/swift-is-like-c-sharp/ by probably someone else. I have not traced the original link.
